[theme]
primaryColor = "#4A69A5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#333333"
font = "Inter"
[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
[logger]
level = "info"
[client]
toolbarMode = "auto"
showErrorDetails = true